.compile interp_missing
.compile pixel_gradient
.compile compute_sht
.compile type3_driftrate_func
.compile roulib
.compile read_rawdam
.compile get_waves_file
.compile read_wind_waves_60s
.compile prep_spect
.compile rabat3_config__define
.compile rabat3_parseconfig
.compile rabat3_getdata
.compile rabat3_getcontour
.compile rabat3_thresholding
.compile rabat3_detect_lig
.compile rabat3_detect_sht
.compile rabat3_processing
.compile rabat3_lesia_processing
